name: Build from Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref == 'refs/heads/main' && github.run_id || github.sha }}-sync
      cancel-in-progress: true
    environment: "production"
    permissions:
      contents: "read"
      id-token: "write"
    env:
      DH_IMAGE_REGISTRY: registry.hub.docker.com
      DAZZLE_VERSION: 0.1.17
      BUILDKIT_VERSION: 0.12.3
      SKOPEO_VERSION: 1.15.2

    steps:
      - name: 📥 Checkout workspace-images
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/workspace-images

      - name: 🔧 Setup tools
        run: |
          sudo apt-get install --yes python3-pip shellcheck
          curl -sSL https://github.com/mvdan/sh/releases/download/v3.5.0/shfmt_v3.5.0_linux_amd64 -o shfmt
          sudo mv shfmt /usr/local/bin/shfmt && sudo chmod +x /usr/local/bin/shfmt
          sudo pip3 install pre-commit

      - name: 🤓 Run pre-commit
        run: |
          pre-commit run --all-files

      - name: 🔆 Install dazzle
        env:
          DAZZLE_VERSION: ${{env.DAZZLE_VERSION}}
        run: |
          curl -sSL "https://github.com/khulnasoft/dazzle/releases/download/v${DAZZLE_VERSION}/dazzle_${DAZZLE_VERSION}_Linux_x86_64.tar.gz" | sudo tar -xvz -C /usr/local/bin

      - name: 🕰️ Create timestamp tag
        id: create-timestamp-tag
        run: |
          echo "TIMESTAMP_TAG=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: 🔆 Install skopeo
        env:
          SKOPEO_VERSION: ${{env.SKOPEO_VERSION}}
        run: |
          sudo apt-get install skopeo -y

      - name: 🏗️ Setup buildkit
        env:
          BUILDKIT_VERSION: ${{env.BUILDKIT_VERSION}}
        run: |
          curl -sSL "https://github.com/moby/buildkit/releases/download/v${BUILDKIT_VERSION}/buildkit-v${BUILDKIT_VERSION}.linux-amd64.tar.gz" | sudo tar xvz -C /usr
          sudo buildkitd --oci-worker=true --oci-worker-net=host --debug --group docker &
          while ! test -S /run/buildkit/buildkitd.sock; do sleep 0.1; done
          sudo chmod +777 /run/buildkit/buildkitd.sock

      - name: 🔨 Dazzle build
        env:
          DH_IMAGE_REGISTRY: ${{env.DH_IMAGE_REGISTRY}}
        run: |
          dazzle build "${DH_IMAGE_REGISTRY}/khulnasoft/docker-dev/workspace-base-images" --chunked-without-hash
          dazzle build "${DH_IMAGE_REGISTRY}/khulnasoft/docker-dev/workspace-base-images"

      - name: 🖇️ Dazzle combine
        env:
          DH_IMAGE_REGISTRY: ${{env.DH_IMAGE_REGISTRY}}
        run: |
          dazzle combine "${DH_IMAGE_REGISTRY}/khulnasoft/docker-dev/workspace-base-images" --all

      - name: 📋 Copy images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DH_IMAGE_REGISTRY: ${{env.DH_IMAGE_REGISTRY}}
        run: |
          skopeo login -u "${DOCKER_USERNAME}" --password "${DOCKER_TOKEN}" "${DH_IMAGE_REGISTRY}"
          skopeo sync --src yaml --retry-times=2 --dest docker .github/promote-images.yml "${DH_IMAGE_REGISTRY}/khulnasoft"
